function toXmldomElement(text){
  var div = document.createElement('div');
  div.innerHTML = text;
  return div.childNodes[0];
}

acceptedTransition  = '<id type="integer">49</id>'
acceptedTransition += '<name>Accepted</name>'
acceptedTransition += '<require_comment type="boolean">false</require_comment>'
acceptedTransition += '<transition_execution_url>http://localhost:4001/api/v2/projects/abc123/transition_executions/49.xml</transition_execution_url>'
acceptedTransition += '<user_input_required type="array">'
acceptedTransition += '</user_input_required>'
acceptedTransition += '<user_input_optional type="array">'
acceptedTransition += '</user_input_optional>'
acceptedTransition += '<if_card_has_properties type="array">'
acceptedTransition += '  <property type_description="Managed text list" hidden="false">'
acceptedTransition += '    <name>Status</name>'
acceptedTransition += '    <value>Ready for Signoff</value>'
acceptedTransition += '  </property>'
acceptedTransition += '</if_card_has_properties>'
acceptedTransition += '<if_card_has_properties_set type="array">'
acceptedTransition += '</if_card_has_properties_set>'
acceptedTransition += '<will_set_card_properties type="array">'
acceptedTransition += '  <property type_description="Managed text list" hidden="false">'
acceptedTransition += '    <name>Status</name>'
acceptedTransition += '    <value>Accepted</value>'
acceptedTransition += '  </property>'
acceptedTransition += '  <property type_description="Automatically generated from the team list" hidden="false">'
acceptedTransition += '    <name>Owner</name>'
acceptedTransition += '    <value nil="true"></value>'
acceptedTransition += '  </property>'
acceptedTransition += '  <property type_description="Date" hidden="true">'
acceptedTransition += '    <name>Date Accepted</name>'
acceptedTransition += '    <value type="date">2010-07-13</value>'
acceptedTransition += '  </property>'
acceptedTransition += '  <property type_description="Card" hidden="true">'
acceptedTransition += '    <name>Sprint Completed</name>'
acceptedTransition += '    <value url="http://localhost:4001/api/v2/projects/abc123/cards/25.xml">'
acceptedTransition += '      <number type="integer">25</number>'
acceptedTransition += '    </value>'
acceptedTransition += '  </property>'
acceptedTransition += '</will_set_card_properties>'
acceptedTransition += '<card_type url="http://localhost:4001/api/v2/projects/abc123/card_types/23.xml">'
acceptedTransition += '  <name>Story</name>'
acceptedTransition += '</card_type>'